name: DragonAuthMe
version: '${project.version}'
main: ltd.dreamcraft.www.DragonAuthMe
commands:
  DragonAuthMe:
  DragonAuthMeAdmin:
    aliases:
      - "dam"
author: haishen668
softdepend: [ DragonCore,AuthMe ]